<?php

namespace Tests\Feature;

use App\Models\StateHistory;
use App\Models\Sticker;
use App\State;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class HistoryApiControllerTest extends TestCase
{
    use RefreshDatabase;

    public function test_index_filter_by_latitude_no_date_returns_correct_history()
    {
        $sticker1 = Sticker::factory()->create(['lat' => 14, 'lon' => 14]);
        $sticker2 = Sticker::factory()->create(['lat' => 20, 'lon' => 20]);
        $sticker3 = Sticker::factory()->create(['lat' => 22, 'lon' => 21]);
        $sticker4 = Sticker::factory()->create(['lat' => 26, 'lon' => 26]);

        $this->travel(10)->minutes();

        $history3 = StateHistory::factory()->create([
            'sticker_id' => $sticker3->id,
            'last_seen' => now(),
            'state' => State::REMOVED,
        ]);

        $response = $this->getJson(route('api.stickers.history.index', ['min_lat' => 15, 'max_lat' => 25, 'min_lon' => 15, 'max_lon' => 25]));

        $response->assertOk()
            ->assertJson([
                'data' => [
                    0 => [
                        'id' => $sticker2->latestStateHistory->id,
                        'sticker_id' => $sticker2->id,
                        'state' => $sticker2->latestStateHistory->state->value,
                        'last_seen' => $sticker2->latestStateHistory->last_seen,
                    ],
                    1 => [
                        'id' => $history3->id,
                        'sticker_id' => $sticker3->id,
                        'state' => $history3->state->value,
                        'last_seen' => $history3->last_seen->format('Y-m-d H:i:s'),
                    ],
                ],
            ]);
    }

    public function test_index_filter_by_latitude_and_date_returns_correct_history()
    {
        Sticker::factory()->create(['lat' => 14, 'lon' => 14]);
        $sticker2 = Sticker::factory()->create(['lat' => 20, 'lon' => 20]);
        $autogeneratedHistory2 = $sticker2->latestStateHistory;
        $sticker3 = Sticker::factory()->create(['lat' => 22, 'lon' => 21]);
        $autogeneratedHistory3 = $sticker3->latestStateHistory;
        $sticker4 = Sticker::factory()->create(['lat' => 22, 'lon' => 23]);
        $autogeneratedHistory4 = $sticker4->latestStateHistory;
        Sticker::factory()->create(['lat' => 26, 'lon' => 26]);

        $this->travel(10)->minutes();

        $history3 = $sticker3->stateHistory()->create([
            'last_seen' => now(),
            'state' => State::REMOVED,
        ]);
        $history4_before = $sticker4->stateHistory()->create([
            'last_seen' => now(),
            'state' => State::PARTIALLY_REMOVED,
        ]);

        $date = now();
        $this->travel(10)->minutes();

        $history4_after = $sticker4->stateHistory()->create([
            'last_seen' => now(),
            'state' => State::REMOVED,
        ]);
        Sticker::factory()->create(['lat' => 19, 'lon' => 21]);

        $response = $this->getJson(route('api.stickers.history.index', ['min_lat' => 15, 'max_lat' => 25, 'min_lon' => 15, 'max_lon' => 25, 'date' => $date->toString()]));

        $response->assertOk()
            ->assertJson([
                'data' => [
                    [
                        'id' => $autogeneratedHistory2->id,
                        'sticker_id' => $sticker2->id,
                        'state' => $autogeneratedHistory2->state->value,
                        'last_seen' => $autogeneratedHistory2->last_seen,
                    ],
                    [
                        'id' => $history3->id,
                        'sticker_id' => $sticker3->id,
                        'state' => $history3->state->value,
                        'last_seen' => $history3->last_seen,
                    ],
                    [
                        'id' => $autogeneratedHistory3->id,
                        'sticker_id' => $sticker3->id,
                        'state' => $autogeneratedHistory3->state->value,
                        'last_seen' => $autogeneratedHistory3->last_seen,
                    ],
                    [
                        'id' => $history4_before->id,
                        'sticker_id' => $sticker4->id,
                        'state' => $history4_before->state->value,
                        'last_seen' => $history4_before->last_seen,
                    ],
                    [
                        'id' => $autogeneratedHistory4->id,
                        'sticker_id' => $sticker4->id,
                        'state' => $autogeneratedHistory4->state->value,
                        'last_seen' => $autogeneratedHistory4->last_seen,
                    ],
                ],
            ]);
    }

    public function test_index_filter_by_invalid_latitude_returns_validation_error()
    {
        $response = $this->getJson(route('api.stickers.history.index', ['min_lat' => -100, 'max_lat' => 110, 'min_lon' => -74, 'max_lon' => 25]));

        $response->assertStatus(422)
            ->assertJsonValidationErrors(['min_lat', 'max_lat']);
    }

    public function test_index_filter_by_invalid_longitude_returns_validation_error()
    {
        $response = $this->getJson(route('api.stickers.history.index', ['min_lat' => -40, 'max_lat' => 60, 'min_lon' => -200, 'max_lon' => 200]));

        $response->assertStatus(422)
            ->assertJsonValidationErrors(['min_lon', 'max_lon']);
    }

    public function test_show_no_date_returns_correct_history()
    {
        $sticker = Sticker::factory()->create(['lat' => 20, 'lon' => 20]);
        $oldestHistory = $sticker->latestStateHistory;

        $this->travel(10)->minutes();

        $history1 = $sticker->stateHistory()->create([
            'last_seen' => now(),
            'state' => State::PARTIALLY_REMOVED,
        ]);

        $this->travel(10)->minutes();

        $response = $this->getJson(route('api.stickers.history.show', ['sticker' => $sticker->id]));

        $response->assertOk()
            ->assertJson([
                'data' => [
                    [
                        'id' => $oldestHistory->id,
                        'sticker_id' => $sticker->id,
                        'state' => $oldestHistory->state->value,
                        'last_seen' => $oldestHistory->last_seen,
                    ],
                    [
                        'id' => $history1->id,
                        'sticker_id' => $sticker->id,
                        'state' => $history1->state->value,
                        'last_seen' => $history1->last_seen,
                    ],
                ],
            ]);
    }

    public function test_show_filter_by_date_returns_correct_history()
    {
        $sticker = Sticker::factory(['lat' => 20, 'lon' => 20])->create();
        $oldestHistory = $sticker->latestStateHistory;

        $this->travel(10)->minutes();

        $history = $sticker->stateHistory()->create([
            'last_seen' => now(),
            'state' => State::PARTIALLY_REMOVED,
        ]);

        $date = now();

        $this->travel(10)->minutes();

        $sticker->stateHistory()->create([
            'last_seen' => now(),
            'state' => State::REMOVED,
        ]);

        $response = $this->getJson(route('api.stickers.history.show', ['sticker' => $sticker->id, 'date' => $date->toString()]));

        $response->assertOk()
            ->assertJson([
                'data' => [
                    [
                        'id' => $oldestHistory->id,
                        'sticker_id' => $sticker->id,
                        'state' => $oldestHistory->state->value,
                        'last_seen' => $oldestHistory->last_seen,
                    ],
                    [
                        'id' => $history->id,
                        'sticker_id' => $sticker->id,
                        'state' => $history->state->value,
                        'last_seen' => $history->last_seen,
                    ],
                ],
            ]);
    }

    public function test_show_history_for_non_existing_sticker_returns_not_found()
    {
        $response = $this->getJson(route('api.stickers.history.show', ['sticker' => 'non-existent-uuid']));

        $response->assertNotFound();
    }

    public function test_update_sticker_history_with_state_creates_and_returns_history()
    {
        $sticker = Sticker::factory(['lat' => 20, 'lon' => 20])->create();

        $this->travel(10)->minutes();

        $history1 = StateHistory::factory()->create([
            'sticker_id' => $sticker->id,
            'last_seen' => now(),
            'state' => State::PARTIALLY_REMOVED,
        ]);

        $this->freezeTime();

        $response = $this->postJson(route('api.stickers.history.update', $sticker->id), ['state' => State::REMOVED]);

        $response->assertCreated()
            ->assertJson([
                'data' => [
                    'id' => $sticker->latestStateHistory->id,
                    'sticker_id' => $sticker->id,
                    'state' => State::REMOVED->value,
                    'last_seen' => now()->setTimezone('UTC')->format('Y-m-d\TH:i:s.u\Z'),
                ],
            ]);
        $this->assertDatabaseHas('state_histories', [
            'sticker_id' => $sticker->id,
            'state' => State::REMOVED->value,
            'last_seen' => now()->format('Y-m-d H:i:s'),
        ]);
    }

    public function test_update_sticker_history_without_state_creates_and_returns_history()
    {
        $sticker = Sticker::factory(['lat' => 20, 'lon' => 20])->create();

        $this->travel(10)->minutes();

        $history1 = StateHistory::factory()->create([
            'sticker_id' => $sticker->id,
            'last_seen' => now(),
            'state' => State::PARTIALLY_REMOVED,
        ]);

        $this->freezeTime();

        $response = $this->postJson(route('api.stickers.history.update', $sticker->id));

        $response->assertCreated()
            ->assertJson([
                'data' => [
                    'id' => $sticker->latestStateHistory->id,
                    'sticker_id' => $sticker->id,
                    'state' => State::PARTIALLY_REMOVED->value,
                    'last_seen' => now()->setTimezone('UTC')->format('Y-m-d\TH:i:s.u\Z'),
                ],
            ]);
        $this->assertDatabaseHas('state_histories', [
            'sticker_id' => $sticker->id,
            'state' => State::PARTIALLY_REMOVED->value,
            'last_seen' => now()->format('Y-m-d H:i:s'),
        ]);
    }

    public function test_update_history_for_non_existing_sticker_returns_not_found()
    {
        $response = $this->postJson(route('api.stickers.history.update', ['sticker' => 'non-existent-uuid']));

        $response->assertNotFound();
    }

    public function test_update_history_with_invalid_state_enum_value_returns_validation_error()
    {
        $sticker = Sticker::factory(['lat' => 20, 'lon' => 20])->create();

        $this->travel(10)->minutes();

        $response = $this->postJson(route('api.stickers.history.update', $sticker->id), ['state' => 'invalid_state']);

        $response->assertStatus(422)
            ->assertJsonValidationErrors(['state']);
    }
}
